"""Build a 2D differential-coil Induction Currents model from a baseline.

The differential-coil topology is an upstream example model. This file is an
independently maintained, parameterized derivation recipe; it does not claim
the upstream model or implementation as original work.

The upstream `.mph` is only a ClientAPI-compatible baseline for the required
AC/DC physics interface. This recipe replaces its mutable model content and
does not treat upstream material values, nonlinear laws, or numerical results
as physically validated.

The baseline must contain a 2D component named ``comp1``, a geometry named
``geom1``, an AC/DC magnetic physics interface tagged ``mf``, and its
default ``fsp1``, ``mi1``, and ``init1`` features. This recipe edits only the
loaded in-memory model and saves a distinct output model. It does not overwrite
the baseline.

By default the recipe builds and saves the model without solving. Pass ``--solve``
only when COMSOL is available and the host is free for a licensed one-point run.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import os
import sys
import uuid
from pathlib import Path

import mph

COIL_WIDTH_MM = 2.0
COIL_HEIGHT_MM = 10.0
COIL_CENTER_X_MM = 6.0
AIR_WIDTH_MM = 80.0
AIR_HEIGHT_MM = 80.0
DEFAULT_FREQUENCY_KHZ = 1.0
REQUIRED_BASELINE_PHYSICS_FEATURES = frozenset({"fsp1", "mi1", "init1"})


def parse_args() -> argparse.Namespace:
    """Parse explicit source, destination, and optional solve controls."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline-model", required=True, type=Path)
    parser.add_argument("--output-model", required=True, type=Path)
    parser.add_argument("--frequency-khz", type=float, default=DEFAULT_FREQUENCY_KHZ)
    parser.add_argument("--solve", action="store_true")
    parser.add_argument("--overwrite-output", action="store_true")
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    """Return a bounded-memory SHA-256 digest for a baseline model file."""
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def require_baseline_contract(model: mph.Model) -> tuple[object, object, object]:
    """Return the required ClientAPI nodes or fail before mutating the model."""
    java_model = model.java
    component = java_model.component().get("comp1")
    geometry = component.geom().get("geom1")
    physics = component.physics().get("mf")
    if str(geometry.getSDim()) != "2":
        raise ValueError("baseline comp1/geom1 must be two-dimensional")

    feature_tags = set(physics.feature().tags())
    required_features = {"fsp1", "mi1", "init1"}
    missing = sorted(required_features - feature_tags)
    if missing:
        raise ValueError(f"baseline mf physics is missing required features: {missing}")
    return java_model, component, geometry


def replace_geometry(geometry: object) -> None:
    """Replace mutable geometry features with the two coils and an air domain."""
    features = geometry.feature()
    existing_tags = [str(tag) for tag in list(features.tags())]
    if "fin" not in existing_tags:
        raise ValueError("baseline geometry is missing its reserved fin feature")
    for tag in existing_tags:
        if tag != "fin":
            features.remove(tag)

    rectangles = (
        ("coil_positive", COIL_CENTER_X_MM, "coil_positive"),
        ("coil_negative", -COIL_CENTER_X_MM, "coil_negative"),
        ("air", 0.0, "air"),
    )
    for tag, center_x, label in rectangles:
        feature = features.create(tag, "Rectangle")
        if tag == "air":
            feature.set("size", [AIR_WIDTH_MM, AIR_HEIGHT_MM])
        else:
            feature.set("size", [COIL_WIDTH_MM, COIL_HEIGHT_MM])
        feature.set("pos", [center_x, 0.0])
        feature.set("base", "center")
        feature.set("selresult", True)
        feature.label(label)
    features.move("fin", int(features.size()) - 1)
    geometry.run()


def named_selection(feature: object, name: str) -> None:
    """Bind a feature to the geometry selection generated by its rectangle."""
    feature.selection().named(f"geom1_{name}_dom")


def replace_physics(component: object, frequency_khz: float) -> None:
    """Configure differential copper coils and a linear-air Ampere law."""
    physics = component.physics().get("mf")
    for tag in list(physics.feature().tags()):
        if str(tag) not in REQUIRED_BASELINE_PHYSICS_FEATURES:
            physics.feature().remove(tag)

    physics.feature().get("fsp1").set("f_typ", f"{frequency_khz}[kHz]")

    ampere_air = physics.feature().create("ampere_air", "AmperesLaw", 2)
    named_selection(ampere_air, "air")
    ampere_air.set("mur", "1")
    ampere_air.set("epsilonr", "1")
    ampere_air.set("epsilonr_mat", "userdef")
    ampere_air.label("Linear air domain")

    for tag, selection_name, current in (
        ("coil_positive", "coil_positive", "1[A]"),
        ("coil_negative", "coil_negative", "-1[A]"),
    ):
        coil = physics.feature().create(tag, "Coil", 2)
        named_selection(coil, selection_name)
        coil.set("ICoil", current)
        coil.set("N", "300")
        coil.set("ConductorModel", "Multi")
        coil.set("sigmaCoil", "6e7[S/m]")
        coil.set("coilWindDiameter", "1[mm]")
        coil.set("FillingFactor", "0.5")
        coil.set("RCoilDC", "50[ohm]")
        coil.set("epsilonr", "1")
        coil.set("epsilonr_mat", "userdef")


def replace_materials(java_model: object, component: object, frequency_khz: float) -> None:
    """Assign air and copper using geometry-result selections, not domain IDs."""
    for tag in list(component.material().tags()):
        component.material().remove(tag)

    air = component.material().create("air", "Common")
    air.propertyGroup("def").set("relpermeability", "1")
    air.propertyGroup("def").set("electricconductivity", "0[S/m]")
    named_selection(air, "air")

    for tag, selection_name in (
        ("copper_positive", "coil_positive"),
        ("copper_negative", "coil_negative"),
    ):
        copper = component.material().create(tag, "Common")
        copper.propertyGroup("def").set("relpermeability", "1")
        copper.propertyGroup("def").set("electricconductivity", "6e7[S/m]")
        named_selection(copper, selection_name)

    java_model.param().set("nu", f"{frequency_khz}[kHz]")
    java_model.param().set("p0", "1[atm]")


def replace_mesh_and_study(java_model: object, component: object, frequency_khz: float) -> None:
    """Build a FreeTri mesh and a one-point frequency-domain study."""
    for tag in list(component.mesh().tags()):
        component.mesh().remove(tag)
    mesh = component.mesh().create("mesh1", "geom1")
    mesh.feature().create("ftri1", "FreeTri")
    mesh.run()

    for tag in list(java_model.study().tags()):
        java_model.study().remove(tag)
    study = java_model.study().create("std1")
    step = study.feature().create("freq", "Frequency")
    step.set("plist", f"{frequency_khz}[kHz]")


def configure_results(java_model: object) -> None:
    """Create a magnetic-flux-density surface plot without evaluating it."""
    for tag in list(java_model.result().tags()):
        java_model.result().remove(tag)
    plot = java_model.result().create("bfield", "PlotGroup2D")
    plot.label("Magnetic Flux Density")
    surface = plot.create("surface", "Surface")
    surface.set("expr", "mf.normB")
    surface.set("unit", "T")


def save_staged_model(java_model: object, output: Path) -> Path:
    """Save a complete model to a unique staging path."""
    staging = output.with_name(f".{output.name}.{uuid.uuid4().hex}.save")
    try:
        java_model.save(str(staging))
        if not staging.is_file() or staging.stat().st_size <= 0:
            raise RuntimeError("COMSOL did not create a complete staging model")
        return staging
    except BaseException:
        staging.unlink(missing_ok=True)
        raise


def publish_staged_model(staging: Path, output: Path, *, overwrite: bool) -> None:
    """Atomically publish one staged model without an accidental overwrite."""
    try:
        if overwrite:
            os.replace(staging, output)
        else:
            os.link(staging, output)
            staging.unlink()
    except BaseException:
        staging.unlink(missing_ok=True)
        raise


def validate_frequency_khz(value: float) -> float:
    """Reject non-finite and non-positive frequency values before model mutation."""
    if not math.isfinite(value) or value <= 0:
        raise ValueError("--frequency-khz must be finite and positive")
    return value


def main() -> None:
    """Build the derived model, optionally solve one point, and save it."""
    args = parse_args()
    baseline = args.baseline_model.resolve()
    output = args.output_model.resolve()
    validate_frequency_khz(args.frequency_khz)
    if not baseline.is_file():
        raise FileNotFoundError(f"baseline model does not exist: {baseline}")
    if baseline == output:
        raise ValueError("--output-model must differ from --baseline-model")
    if output.exists() and not args.overwrite_output:
        raise FileExistsError(
            "--output-model already exists; pass --overwrite-output to replace it"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    baseline_sha256 = sha256_file(baseline)

    client = mph.Client(version="6.4")
    model = client.load(str(baseline))
    staging = None
    try:
        java_model, component, geometry = require_baseline_contract(model)
        replace_geometry(geometry)
        replace_physics(component, args.frequency_khz)
        replace_materials(java_model, component, args.frequency_khz)
        replace_mesh_and_study(java_model, component, args.frequency_khz)
        configure_results(java_model)
        if args.solve:
            java_model.study("std1").run()
            values = model.evaluate("mf.normB", "T")
            print(f"Solved; max mf.normB = {max(values):.6g} T", flush=True)
        staging = save_staged_model(java_model, output)
    finally:
        client.remove(model)

    if sha256_file(baseline) != baseline_sha256:
        if staging is not None:
            staging.unlink(missing_ok=True)
        raise RuntimeError("baseline model changed while building the derived model")
    if staging is None:
        raise RuntimeError("derived model staging did not complete")
    publish_staged_model(staging, output, overwrite=args.overwrite_output)
    print(f"Saved derived model: {output} (baseline SHA-256: {baseline_sha256})", flush=True)


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"Recipe failed: {error}", file=sys.stderr, flush=True)
        raise
