"""Solver-free surrogate dataset, split, schema, and transform contracts."""

from __future__ import annotations

__all__ = [
    "DEFAULT_PROPORTIONS",
    "DRIFT_IDENTITY_FIELDS",
    "ESCALATION_REQUIRED_STATES",
    "IneligibleRow",
    "LEAKAGE_CLASSES",
    "LIFECYCLE_STATES",
    "LeakageGroup",
    "OOD_STATES",
    "SCIENTIFIC_STATES",
    "SPLIT_NAMES",
    "STRATEGY_VERSION",
    "SplitAssignment",
    "SurrogateDatasetManifest",
    "SurrogateSchemaManifest",
    "SurrogateTrainingTransforms",
    "TERMINAL_ERROR_STATES",
    "advance_registry_entry",
    "apply_transforms",
    "assert_no_contract_drift",
    "assert_no_leakage",
    "assert_prediction_not_evidence",
    "assign_group_disjoint_split",
    "build_dataset_manifest",
    "build_field_schema",
    "build_model_card",
    "build_registry_entry",
    "build_schema_manifest",
    "build_training_transforms",
    "canonical_manifest_sha256",
    "detect_drift",
    "detect_leakage",
    "evaluate_ood",
    "fit_transforms",
    "invert_transforms",
    "validate_dataset_manifest",
    "validate_field_schema",
    "validate_fitted_transforms",
    "validate_group_disjoint_split",
    "validate_model_card",
    "validate_registry_entry",
    "validate_schema_manifest",
    "validate_split_plan",
    "validate_training_transforms",
    "verify_transform_roundtrip",
]

from comsol_mcp.surrogate.fields import (
    apply_transforms,
    build_field_schema,
    fit_transforms,
    invert_transforms,
    validate_field_schema,
    validate_fitted_transforms,
    verify_transform_roundtrip,
)
from comsol_mcp.surrogate.manifests import (
    IneligibleRow,
    LeakageGroup,
    SplitAssignment,
    SurrogateDatasetManifest,
    SurrogateSchemaManifest,
    SurrogateTrainingTransforms,
    build_dataset_manifest,
    build_schema_manifest,
    build_training_transforms,
    canonical_manifest_sha256,
    validate_dataset_manifest,
    validate_group_disjoint_split,
    validate_schema_manifest,
    validate_training_transforms,
)
from comsol_mcp.surrogate.registry import (
    DRIFT_IDENTITY_FIELDS,
    ESCALATION_REQUIRED_STATES,
    LIFECYCLE_STATES,
    OOD_STATES,
    SCIENTIFIC_STATES,
    TERMINAL_ERROR_STATES,
    advance_registry_entry,
    assert_no_contract_drift,
    assert_prediction_not_evidence,
    build_model_card,
    build_registry_entry,
    detect_drift,
    evaluate_ood,
    validate_model_card,
    validate_registry_entry,
)
from comsol_mcp.surrogate.splits import (
    DEFAULT_PROPORTIONS,
    LEAKAGE_CLASSES,
    SPLIT_NAMES,
    STRATEGY_VERSION,
    assert_no_leakage,
    assign_group_disjoint_split,
    detect_leakage,
    validate_split_plan,
)
