"""Solver-free surrogate dataset, split, schema, transform, and row contracts."""

from __future__ import annotations

__all__ = [
    "DEFAULT_PROPORTIONS",
    "DRIFT_IDENTITY_FIELDS",
    "ESCALATION_REQUIRED_STATES",
    "INELIGIBLE_REASON_CODES",
    "IneligibleRow",
    "LEAKAGE_CLASSES",
    "LHS_STRATEGY_VERSION",
    "LIFECYCLE_STATES",
    "LeakageGroup",
    "OOD_STATES",
    "ROW_EVIDENCE_STATES",
    "ROW_IDENTITY_FIELDS",
    "SCIENTIFIC_STATES",
    "SPLIT_NAMES",
    "STRATEGY_VERSION",
    "SplitAssignment",
    "SurrogateDatasetManifest",
    "SurrogateSchemaManifest",
    "SurrogateTrainingTransforms",
    "TERMINAL_ERROR_STATES",
    "advance_registry_entry",
    "apply_transforms",
    "assert_design_within_bounds",
    "assert_no_contract_drift",
    "assert_no_leakage",
    "assert_prediction_not_evidence",
    "assign_group_disjoint_split",
    "assert_no_prediction_promotion",
    "build_campaign_spec",
    "build_dataset_manifest",
    "build_field_schema",
    "build_lhs_design",
    "build_model_card",
    "build_registry_entry",
    "build_row_provenance",
    "build_screening_record",
    "build_schema_manifest",
    "build_training_transforms",
    "CANDIDATE_STATES",
    "canonical_manifest_sha256",
    "check_prediction_consistency",
    "CONSISTENCY_STATES",
    "compare_against_baseline",
    "compute_metrics",
    "CONTINUATION_IDENTITY_FIELDS",
    "detect_drift",
    "detect_leakage",
    "evaluate_continuation",
    "evaluate_export_availability",
    "evaluate_ood",
    "evaluate_seed_stability",
    "EXPORT_FORMATS",
    "fit_baseline",
    "fit_transforms",
    "hash_export_artifact",
    "integrate_export_into_registry",
    "invert_transforms",
    "MAX_CANDIDATES",
    "MAX_FEM_ESCALATIONS",
    "MAX_TOP_K",
    "MAX_WALL_TIME_SECONDS",
    "METRIC_NAMES",
    "OnnxDecodeError",
    "predict_baseline",
    "rank_candidates",
    "record_fem_result",
    "summarize_campaign",
    "summarize_row_ledger",
    "train_surrogate",
    "validate_campaign_spec",
    "validate_dataset_manifest",
    "validate_export_manifest",
    "validate_field_schema",
    "validate_fitted_transforms",
    "validate_group_disjoint_split",
    "validate_lhs_design",
    "validate_model_card",
    "validate_registry_entry",
    "validate_row_provenance",
    "validate_schema_manifest",
    "validate_screening_record",
    "validate_split_plan",
    "validate_training_transforms",
    "verify_transform_roundtrip",
]

from comsol_mcp.surrogate.onnx_runtime import (
    OnnxDecodeError,
    evaluate_onnx_model,
    load_onnx_model,
)

from comsol_mcp.surrogate.campaign import (
    CANDIDATE_STATES,
    MAX_CANDIDATES,
    MAX_FEM_ESCALATIONS,
    MAX_TOP_K,
    MAX_WALL_TIME_SECONDS,
    assert_no_prediction_promotion,
    build_campaign_spec,
    build_screening_record,
    rank_candidates,
    record_fem_result,
    summarize_campaign,
    validate_campaign_spec,
    validate_screening_record,
)

from comsol_mcp.surrogate.export import (
    CONSISTENCY_STATES,
    EXPORT_FORMATS,
    build_export_manifest,
    check_prediction_consistency,
    evaluate_export_availability,
    hash_export_artifact,
    integrate_export_into_registry,
    validate_export_manifest,
)
from comsol_mcp.surrogate.fields import (
    apply_transforms,
    build_field_schema,
    fit_transforms,
    invert_transforms,
    validate_field_schema,
    validate_fitted_transforms,
    verify_transform_roundtrip,
)
from comsol_mcp.surrogate.manifests import (
    IneligibleRow,
    LeakageGroup,
    SplitAssignment,
    SurrogateDatasetManifest,
    SurrogateSchemaManifest,
    SurrogateTrainingTransforms,
    build_dataset_manifest,
    build_schema_manifest,
    build_training_transforms,
    canonical_manifest_sha256,
    validate_dataset_manifest,
    validate_group_disjoint_split,
    validate_schema_manifest,
    validate_training_transforms,
)
from comsol_mcp.surrogate.registry import (
    DRIFT_IDENTITY_FIELDS,
    ESCALATION_REQUIRED_STATES,
    LIFECYCLE_STATES,
    OOD_STATES,
    SCIENTIFIC_STATES,
    TERMINAL_ERROR_STATES,
    advance_registry_entry,
    assert_no_contract_drift,
    assert_prediction_not_evidence,
    build_model_card,
    build_registry_entry,
    detect_drift,
    evaluate_ood,
    validate_model_card,
    validate_registry_entry,
)
from comsol_mcp.surrogate.rows import (
    INELIGIBLE_REASON_CODES,
    ROW_EVIDENCE_STATES,
    ROW_IDENTITY_FIELDS,
    assert_design_within_bounds,
    build_lhs_design,
    build_row_provenance,
    summarize_row_ledger,
    validate_lhs_design,
    validate_row_provenance,
)
from comsol_mcp.surrogate.rows import STRATEGY_VERSION as LHS_STRATEGY_VERSION
from comsol_mcp.surrogate.training import (
    CONTINUATION_IDENTITY_FIELDS,
    METRIC_NAMES,
    compare_against_baseline,
    compute_metrics,
    evaluate_continuation,
    evaluate_seed_stability,
    fit_baseline,
    predict_baseline,
)
from comsol_mcp.surrogate.dnn_adapter import train_surrogate
from comsol_mcp.surrogate.splits import (
    DEFAULT_PROPORTIONS,
    LEAKAGE_CLASSES,
    SPLIT_NAMES,
    STRATEGY_VERSION,
    assert_no_leakage,
    assign_group_disjoint_split,
    detect_leakage,
    validate_split_plan,
)
