"""Solver-free contracts for bounded goal-directed research campaigns."""

from .adapters import (
    STRUCTURE_ADAPTER_APPLICATION_SCHEMA_NAME,
    STRUCTURE_ADAPTER_APPLICATION_SCHEMA_VERSION,
    STRUCTURE_ADAPTER_MANIFEST_SCHEMA_NAME,
    STRUCTURE_ADAPTER_MANIFEST_SCHEMA_VERSION,
    STRUCTURE_TREE_AUDIT_SCHEMA_NAME,
    STRUCTURE_TREE_AUDIT_SCHEMA_VERSION,
    ClientapiPeriodicMimPatchBackend,
    adapter_state_sha256,
    apply_periodic_mim_patch_candidate,
    normalize_structure_adapter_manifest,
    normalize_structure_tree_audit,
)
from .adjoint_adapter import ADJOINT_ADAPTER_ID, ADJOINT_ADAPTER_VERSION, configure_native_adjoint
from .compiler import (
    CAMPAIGN_MANIFEST_SCHEMA_NAME,
    CAMPAIGN_MANIFEST_SCHEMA_VERSION,
    compile_campaign_manifest,
)
from .contracts import (
    DESIGN_SPACE_SCHEMA_NAME,
    DESIGN_SPACE_SCHEMA_VERSION,
    RESEARCH_GOAL_SCHEMA_NAME,
    RESEARCH_GOAL_SCHEMA_VERSION,
    normalize_design_space,
    normalize_research_goal,
    relative_bounds,
)
from .decisions import (
    DECISION_RECORD_SCHEMA_NAME,
    DECISION_RECORD_SCHEMA_VERSION,
    normalize_decision_record,
)
from .derivative_support import (
    DERIVATIVE_CONSTRAINT_SCHEMA_NAME,
    DERIVATIVE_CONSTRAINT_SCHEMA_VERSION,
    DERIVATIVE_OBJECTIVE_SCHEMA_NAME,
    DERIVATIVE_OBJECTIVE_SCHEMA_VERSION,
    DERIVATIVE_SUPPORT_SCHEMA_NAME,
    DERIVATIVE_SUPPORT_SCHEMA_VERSION,
    DERIVATIVE_VARIABLE_SCHEMA_NAME,
    DERIVATIVE_VARIABLE_SCHEMA_VERSION,
    normalize_derivative_constraint,
    normalize_derivative_objective,
    normalize_derivative_support,
    normalize_derivative_variable,
)
from .evaluations import (
    EVALUATION_RECORD_SCHEMA_NAME,
    EVALUATION_RECORD_SCHEMA_VERSION,
    normalize_evaluation_record,
)
from .gradient_contracts import (
    GRADIENT_RECORD_SCHEMA_NAME,
    GRADIENT_RECORD_SCHEMA_VERSION,
    NATIVE_OPTIMIZER_SCHEMA_NAME,
    NATIVE_OPTIMIZER_SCHEMA_VERSION,
    normalize_gradient_record,
    normalize_native_optimizer_configuration,
)
from .gradient_validation import (
    GRADIENT_CHECK_SCHEMA_NAME,
    GRADIENT_CHECK_SCHEMA_VERSION,
    compare_directional_gradient,
    compare_gradient,
)
from .journal import (
    RESEARCH_JOURNAL_RECORD_SCHEMA_NAME,
    RESEARCH_JOURNAL_RECORD_SCHEMA_VERSION,
    append_research_journal_record,
    recover_research_journal,
)
from .materials import (
    MATERIAL_CATALOG_SCHEMA_NAME,
    MATERIAL_CATALOG_SCHEMA_VERSION,
    normalize_material_catalog,
)
from .objectives import (
    OBJECTIVE_SCORE_SCHEMA_NAME,
    OBJECTIVE_SCORE_SCHEMA_VERSION,
    score_objectives,
)
from .optimizers import (
    OPTIMIZER_EXPLANATION_SCHEMA_NAME,
    OPTIMIZER_EXPLANATION_SCHEMA_VERSION,
    OPTIMIZER_PROPOSAL_SCHEMA_NAME,
    OPTIMIZER_PROPOSAL_SCHEMA_VERSION,
    OPTIMIZER_STATE_SCHEMA_NAME,
    OPTIMIZER_STATE_SCHEMA_VERSION,
    DeterministicGridOptimizer,
    DeterministicLatinHypercubeOptimizer,
    DeterministicRandomOptimizer,
    ResearchOptimizerProtocol,
)
from .records import (
    CANDIDATE_RECORD_SCHEMA_NAME,
    CANDIDATE_RECORD_SCHEMA_VERSION,
    normalize_candidate_record,
)
from .state import (
    OPTIMIZER_CHECKPOINT_SCHEMA_NAME,
    OPTIMIZER_CHECKPOINT_SCHEMA_VERSION,
    PORTFOLIO_SCHEMA_NAME,
    PORTFOLIO_SCHEMA_VERSION,
    normalize_optimizer_checkpoint,
    normalize_portfolio,
)
from .workflow import (
    WORKFLOW_CAPSULE_SCHEMA_NAME,
    WORKFLOW_CAPSULE_SCHEMA_VERSION,
    normalize_workflow_capsule,
)

__all__ = [
    "ClientapiPeriodicMimPatchBackend",
    "ADJOINT_ADAPTER_ID",
    "ADJOINT_ADAPTER_VERSION",
    "STRUCTURE_ADAPTER_APPLICATION_SCHEMA_NAME",
    "STRUCTURE_ADAPTER_APPLICATION_SCHEMA_VERSION",
    "STRUCTURE_ADAPTER_MANIFEST_SCHEMA_NAME",
    "STRUCTURE_ADAPTER_MANIFEST_SCHEMA_VERSION",
    "STRUCTURE_TREE_AUDIT_SCHEMA_NAME",
    "STRUCTURE_TREE_AUDIT_SCHEMA_VERSION",
    "DESIGN_SPACE_SCHEMA_NAME",
    "DESIGN_SPACE_SCHEMA_VERSION",
    "EVALUATION_RECORD_SCHEMA_NAME",
    "EVALUATION_RECORD_SCHEMA_VERSION",
    "DECISION_RECORD_SCHEMA_NAME",
    "DECISION_RECORD_SCHEMA_VERSION",
    "DERIVATIVE_CONSTRAINT_SCHEMA_NAME",
    "DERIVATIVE_CONSTRAINT_SCHEMA_VERSION",
    "DERIVATIVE_OBJECTIVE_SCHEMA_NAME",
    "DERIVATIVE_OBJECTIVE_SCHEMA_VERSION",
    "DERIVATIVE_SUPPORT_SCHEMA_NAME",
    "DERIVATIVE_SUPPORT_SCHEMA_VERSION",
    "DERIVATIVE_VARIABLE_SCHEMA_NAME",
    "DERIVATIVE_VARIABLE_SCHEMA_VERSION",
    "MATERIAL_CATALOG_SCHEMA_NAME",
    "MATERIAL_CATALOG_SCHEMA_VERSION",
    "GRADIENT_RECORD_SCHEMA_NAME",
    "GRADIENT_RECORD_SCHEMA_VERSION",
    "GRADIENT_CHECK_SCHEMA_NAME",
    "GRADIENT_CHECK_SCHEMA_VERSION",
    "NATIVE_OPTIMIZER_SCHEMA_NAME",
    "NATIVE_OPTIMIZER_SCHEMA_VERSION",
    "OPTIMIZER_CHECKPOINT_SCHEMA_NAME",
    "OPTIMIZER_CHECKPOINT_SCHEMA_VERSION",
    "OPTIMIZER_EXPLANATION_SCHEMA_NAME",
    "OPTIMIZER_EXPLANATION_SCHEMA_VERSION",
    "OPTIMIZER_PROPOSAL_SCHEMA_NAME",
    "OPTIMIZER_PROPOSAL_SCHEMA_VERSION",
    "OPTIMIZER_STATE_SCHEMA_NAME",
    "OPTIMIZER_STATE_SCHEMA_VERSION",
    "OBJECTIVE_SCORE_SCHEMA_NAME",
    "OBJECTIVE_SCORE_SCHEMA_VERSION",
    "PORTFOLIO_SCHEMA_NAME",
    "PORTFOLIO_SCHEMA_VERSION",
    "DeterministicGridOptimizer",
    "DeterministicLatinHypercubeOptimizer",
    "DeterministicRandomOptimizer",
    "ResearchOptimizerProtocol",
    "CAMPAIGN_MANIFEST_SCHEMA_NAME",
    "CAMPAIGN_MANIFEST_SCHEMA_VERSION",
    "CANDIDATE_RECORD_SCHEMA_NAME",
    "CANDIDATE_RECORD_SCHEMA_VERSION",
    "RESEARCH_GOAL_SCHEMA_NAME",
    "RESEARCH_GOAL_SCHEMA_VERSION",
    "RESEARCH_JOURNAL_RECORD_SCHEMA_NAME",
    "RESEARCH_JOURNAL_RECORD_SCHEMA_VERSION",
    "WORKFLOW_CAPSULE_SCHEMA_NAME",
    "WORKFLOW_CAPSULE_SCHEMA_VERSION",
    "adapter_state_sha256",
    "apply_periodic_mim_patch_candidate",
    "normalize_design_space",
    "normalize_structure_adapter_manifest",
    "normalize_structure_tree_audit",
    "normalize_decision_record",
    "normalize_derivative_constraint",
    "normalize_derivative_objective",
    "normalize_derivative_support",
    "normalize_derivative_variable",
    "normalize_evaluation_record",
    "normalize_material_catalog",
    "normalize_gradient_record",
    "normalize_native_optimizer_configuration",
    "compare_gradient",
    "compare_directional_gradient",
    "normalize_optimizer_checkpoint",
    "normalize_portfolio",
    "normalize_candidate_record",
    "normalize_research_goal",
    "normalize_workflow_capsule",
    "append_research_journal_record",
    "recover_research_journal",
    "relative_bounds",
    "score_objectives",
    "compile_campaign_manifest",
    "configure_native_adjoint",
]
